config/routes.rb
Recipebook::Application.routes.draw do
  get "recipes/index"
  get "recipes/new"
  get "home/index"

  root 'home#index'

  resources :recipes

end

app/models/recipes.rb
class Recipes < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  	@allRecipes = Recipes.all
  end

  def new
  	@recipe = Recipes.new
  end

  def recipe_params
  	params.require(:recipes).permit(:title, :description, :difficulty, :ingredients, :method, :serves)
  end

  def create
  	@recipe = Recipes.new(recipe_params)

  	if @recipe.save
  		redirect_to recipes_path, :notice => "Your recipe was added"
  	else
  		render "new"
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<h1>Recipe Book Homepage</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Recipebook" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
 <div class="container">
        <div class="row">
          <div class="span12">
    <div class="navbar navbar-top-fixed">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
        
          <%= link_to "Recipebook", root_path, :class => 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "All Recipes", recipes_path %></li>
              <li><%= link_to "Add Recipe", recipes_new_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    </div></div></div>





    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/recipes/index.html.erb
<h1>Recipes List</h1>
<p>Find me in app/views/recipes/index.html.erb</p>

<% @allRecipes.each do |r| %>

<table class="table table-striped table-hover table-bordered">
	<tr>
		<td><h3><%= r.title %></h3></td>
	</tr>
	<tr>
		<td><p>Difficulty: <%= r.difficulty %> - Serves: <%= r.serves %></p></td>
	</tr>

	<tr>
		<td>
			<p><%= r.description %></p>
		</td>
	</tr>

	<tr>
		<td>
			<p>Ingredients: <%= r.ingredients %></p>
		</td>
	</tr>

	<tr>
		<td>
			<p>Method: <%= r.method %></p>		
		</td>
	</tr>

</table>
<hr/>
<% end %>

app/views/recipes/new.html.erb
<h1>Add a new recipe</h1>
<p>Find me in app/views/recipes/new.html.erb</p>

<%= form_for @recipe, :url => recipes_path do |r| %>

	<%= r.label :title %> <%= r.text_field :title %>

	<%= r.label :description %> <%= r.text_area :description %>

	<%= r.label :difficulty %> <%= r.text_field :difficulty %>

	<%= r.label :ingredients %> <%= r.text_area :ingredients %>

	<%= r.label :method %> <%= r.text_area :method %>

	<%= r.label :serves %> <%= r.text_field :serves %>

	<p><%= r.submit "Submit Recipe", :class => "btn btn-success" %></p>

<% end %>